/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panjq_opencv_alg_ImagePro */

#ifndef _Included_com_panjq_opencv_alg_ImagePro
#define _Included_com_panjq_opencv_alg_ImagePro
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jintArray JNICALL Java_com_panjq_opencv_alg_ImagePro_caffe2init(
        JNIEnv* env,
        jobject /* this */,
        jobject assetManager);
/*
 * Class:     com_panjq_opencv_alg_ImagePro
 * Method:    jniImagePro3
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_panjq_opencv_alg_ImagePro_caffe2inference
        (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
